name: E2Eテスト
on: push

jobs:
  test:
    name: E2Eテスト
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
#        os: [ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
#        browser: ['safari:MAC', 'safari:mac', 'chrome', 'firefox:WINDOWS', 'opera:WINDOWS']
        browser: ['safari@3.0.3:mac']
    services:
      selenium:
        image: selenium/standalone-chrome:3.141.59-vanadium
        ports:
          - 4444:4444
        volumes:
          - /dev/shm:/dev/shm
    steps:
      - name: ブランチをチェックアウト
        uses: actions/checkout@master
      - name: Node.jsのセットアップ
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
#      - name: yarnのキャッシュディレクトリパスを取得
#        id: yarn-cache
#        run: echo "::set-output name=dir::$(yarn cache dir)"
#      - name: node_modulesキャッシュ設定
#        uses: actions/cache@v1
#        with:
#          path: ${{ steps.yarn-cache.outputs.dir }}
#          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
#          restore-keys: |
#            ${{ runner.os }}-yarn-
#      - name: パッケージインストール
#        run: yarn install
#      - name: TestCafeを実行
#        run: yarn testcafe "chrome:headless" e2e -s takeOnFails=true
      - name: Install Selenium provider
        run: yarn add testcafe-browser-provider-selenium
      - name: TestCafe実行
        uses: DevExpress/testcafe-action@latest
        with:
          args: selenium:${{ matrix.browser }} e2e -s takeOnFails=true
      - name: テスト失敗時のスクリーンショットを保存
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: e2e-screenshots
          path: screenshots
