name: ESLintチェック
on: push

jobs:
  build:
    name: ESLintチェック
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install
      - run: yarn run lint --fix --max-warnings 0
