name: PullRequestの内容をプレビュー
on: pull_request
#    paths:
#      - src/**
#      - nuxt.config.ts
#      - package.json

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_S3_BUCKET: gh-actions-playground-pr-preview
    steps:
      - name: ブランチをチェックアウト
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Node.jsのセットアップ
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: yarnのキャッシュディレクトリパスを取得
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: node_modulesキャッシュ設定
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: ビルドキャッシュの設定
        uses: actions/cache@v1
        with:
          path: node_modules/.cache
          key: ${{ runner.os }}-${{ github.ref }}-cache
      - name: パッケージインストール
        run: yarn install
      - name: 静的ビルド
        run: yarn build --analyze
        env:
          BASE_PATH: ${{ toJSON(env).AWS_S3_BUCKET }}
      - name: デプロイ
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: s3 sync $SOURCE_DIR s3://$AWS_S3_BUCKET/$GITHUB_HEAD_REF --acl public-read
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-1
          SOURCE_DIR: ./dist
      - name: ビルドファイルの統計を保存
        uses: actions/upload-artifact@v1
        with:
          name: stats
          path: .nuxt/stats
